import { DateTime } from "luxon";
import {
  ResumeSkill,
  ResumeSkillProficiency,
  ResumeSkillType,
  ResumeType,
} from "./types";
import { yyyyMMdd } from "~/constants/dates";

export const skills: ResumeSkill[] = [
  {
    id: 1,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "JavaScript",
    startDate: DateTime.fromFormat("2007-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 2,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "TypeScript",
    startDate: DateTime.fromFormat("2017-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 3,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "Python",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
    subtitle: "Including: 2, 3, pydantic",
  },
  {
    id: 4,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "Ruby",
    startDate: DateTime.fromFormat("2020-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 5,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "Java",
    startDate: DateTime.fromFormat("2008-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 6,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "HTML",
    startDate: DateTime.fromFormat("1997-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 7,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "node",
    startDate: DateTime.fromFormat("2015-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 8,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "bun",
    startDate: DateTime.fromFormat("2024-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 9,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "Django",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 10,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorDataEngineer,
    ],
    title: "C++",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 11,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorDataEngineer,
    ],
    title: "Rust",
    startDate: DateTime.fromFormat("2022-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 12,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "R",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 13,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "React",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 14,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "Remix",
    startDate: DateTime.fromFormat("2023-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 15,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
    ],
    title: "Next.js",
    startDate: DateTime.fromFormat("2021-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 16,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "PyTorch",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 17,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "TensorFlow",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 18,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "scikit-learn",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 19,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
    ],
    title: "pandas",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 20,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
    ],
    title: "numpy",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 21,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "spaCy",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 22,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "fastai",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 23,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
    ],
    title: "Hugging Face",
    startDate: DateTime.fromFormat("2021-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 24,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Apache Spark (pySpark)",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 25,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Apache Kafka",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 26,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GCP PubSub",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 27,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "AWS Kinesis",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 28,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "AWS Glue",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 29,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "AWS S3",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 30,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "AWS Redshift",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 31,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "gRPC",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 32,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Kubernetes",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 33,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Docker",
    startDate: DateTime.fromFormat("2015-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 34,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Git",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 35,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GitHub",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 36,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GitLab",
    startDate: DateTime.fromFormat("2012-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 37,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Airflow",
    startDate: DateTime.fromFormat("2020-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 38,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Terraform",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 39,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Jenkins",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 40,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GitHub Actions",
    startDate: DateTime.fromFormat("2020-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 41,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "PostgreSQL",
    startDate: DateTime.fromFormat("2014-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 42,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Aurora",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 43,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "MongoDB",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Expert,
  },
  {
    id: 44,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Redis",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 45,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "BigQuery",
    startDate: DateTime.fromFormat("2019-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 46,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "MySQL",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 47,
    skillType: ResumeSkillType.Methodology,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Agile",
    startDate: DateTime.fromFormat("2014-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 48,
    skillType: ResumeSkillType.Methodology,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "CI/CD",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 49,
    skillType: ResumeSkillType.FrameworksAndRuntimes,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Spring Boot",
    startDate: DateTime.fromFormat("2015-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 50,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GCP Cloud Functions",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 51,
    skillType: ResumeSkillType.MachineLearningAndDataEngineering,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorDataEngineer,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.MachineLearningEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GCP Cloud Storage",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 52,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Haskell",
    startDate: DateTime.fromFormat("2021-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2022-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 53,
    skillType: ResumeSkillType.Other,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Cardano Smart Contracts",
    startDate: DateTime.fromFormat("2021-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2022-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 54,
    skillType: ResumeSkillType.Database,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Neo4j",
    startDate: DateTime.fromFormat("2019-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2023-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 55,
    skillType: ResumeSkillType.Libraries,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "GraphQL",
    subtitle: "Including: Apollo, Prisma",
    startDate: DateTime.fromFormat("2018-01-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 56,
    skillType: ResumeSkillType.DevOps,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
      ResumeType.MachineLearningEngineer,
    ],
    title: "Slurm (resource management)",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2019-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Intermediate,
  },
  {
    id: 57,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "CUDA C++",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2019-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 58,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "OpenMP",
    subtitle: "Including: C++ and Fortran",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2019-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 59,
    skillType: ResumeSkillType.Languages,
    resumeTypes: [
      ResumeType.Architect,
      ResumeType.SeniorFullstackEngineer,
      ResumeType.SeniorBackendEngineer,
      ResumeType.SeniorSoftwareEngineer,
    ],
    title: "Assembly",
    subtitle: "Including: x86 and MIPS",
    startDate: DateTime.fromFormat("2016-01-01", yyyyMMdd),
    endDate: DateTime.fromFormat("2019-12-31", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Basic,
  },
  {
    id: 60,
    skillType: ResumeSkillType.TherapyModalities,
    resumeTypes: [ResumeType.Therapist],
    title: "Cognitive Behavioral Therapy (CBT)",
    startDate: DateTime.fromFormat("2001-08-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 61,
    skillType: ResumeSkillType.TherapyModalities,
    resumeTypes: [ResumeType.Therapist],
    title: "Group-Based Cognitive Behavioral Therapy (CBT)",
    startDate: DateTime.fromFormat("2001-08-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
  {
    id: 62,
    skillType: ResumeSkillType.TherapyModalities,
    resumeTypes: [ResumeType.Therapist],
    title: "Aging and Family Therapy",
    startDate: DateTime.fromFormat("2001-08-01", yyyyMMdd),
    profieciency: ResumeSkillProficiency.Advanced,
  },
];
